"""
Seed the SQLite DB with sample briefing data for Streamlit Cloud demo.
Run once from project root: python scripts/seed_sample_data.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import database as db

RUNS = [
    {
        "timestamp": "2026-04-30T07:02:11.482193+00:00",
        "articles": [
            {
                "title": "GPT-4o Gets Smarter: OpenAI Rolls Out Improved Reasoning for All Users",
                "url": "https://techcrunch.com/2026/04/30/gpt4o-improved-reasoning",
                "source_name": "TechCrunch AI",
                "source_tier": 1,
                "published_at": "2026-04-30T06:00:00+00:00",
                "score": 8,
                "score_reason": "Direct capability improvement from a top lab, affects all developers",
                "category": "ai_news",
                "summary": "OpenAI pushed an update to GPT-4o improving multi-step reasoning and reducing hallucination rates by 18% on internal benchmarks. The update is live for all free and paid users with no API changes required. Engineers using GPT-4o in production chains should expect more reliable structured outputs.",
            },
            {
                "title": "Google DeepMind's AlphaFold 3 Predicts Drug Interactions at Atomic Scale",
                "url": "https://venturebeat.com/ai/deepmind-alphafold3-drug-interactions",
                "source_name": "VentureBeat AI",
                "source_tier": 1,
                "published_at": "2026-04-30T08:15:00+00:00",
                "score": 8,
                "score_reason": "Major scientific milestone with direct applications in AI-for-science",
                "category": "ai_news",
                "summary": "AlphaFold 3 now predicts how small-molecule drugs bind to protein targets at atomic precision, enabling faster drug discovery pipelines. DeepMind released a public API for academic use. This extends AI's reach from protein structure prediction to full molecular interaction modeling.",
            },
            {
                "title": "Mixture-of-Experts at Scale: Lessons from Training a 400B Sparse Model",
                "url": "https://arxiv.org/abs/2604.20001",
                "source_name": "arXiv cs.AI",
                "source_tier": 1,
                "published_at": "2026-04-30T00:00:00+00:00",
                "score": 7,
                "score_reason": "Practical MoE engineering lessons applicable to production sparse models",
                "category": "ai_news",
                "summary": "Researchers detail training instabilities, routing collapse, and load imbalance solutions encountered building a 400B sparse MoE model. Key finding: auxiliary loss weight above 0.01 causes gradient interference; a separate router learning rate is necessary. All training code is open-sourced.",
            },
            {
                "title": "How I Landed a Senior ML Engineer Role Using Side Projects as Leverage",
                "url": "https://news.ycombinator.com/item?id=43000001",
                "source_name": "HackerNews",
                "source_tier": 2,
                "published_at": "2026-04-29T20:00:00+00:00",
                "score": 7,
                "score_reason": "Concrete job-hunt strategy directly relevant to current career goals",
                "category": "career",
                "summary": "A senior ML engineer shares how personal AI projects served as conversation anchors in every interview, replacing the need for big-company brand names. The author emphasizes documenting architecture decisions and showing metrics rather than just code. Hiring managers confirmed they weight demonstrated judgment over credentials.",
            },
            {
                "title": "What Interviewers Actually Look for in AI/ML System Design Rounds",
                "url": "https://venturebeat.com/ai/ml-system-design-interviews-2026",
                "source_name": "VentureBeat AI",
                "source_tier": 1,
                "published_at": "2026-04-30T09:00:00+00:00",
                "score": 7,
                "score_reason": "Directly actionable interview prep for AI engineering roles",
                "category": "career",
                "summary": "A guide based on 200+ interview debrief notes reveals that candidates who fail ML system design rounds typically over-index on model choice and skip data pipeline and evaluation design. Top performers spend the first 5 minutes clarifying latency, throughput, and freshness requirements. RAG and agent systems are now standard interview topics.",
            },
            {
                "title": "Sam Altman: AGI Is Closer Than Most Researchers Think",
                "url": "https://techcrunch.com/2026/04/30/altman-agi-timeline",
                "source_name": "TechCrunch AI",
                "source_tier": 1,
                "published_at": "2026-04-30T10:30:00+00:00",
                "score": 6,
                "score_reason": "CEO timeline statement shapes market expectations and hiring",
                "category": "ceo_update",
                "summary": "Sam Altman said in a Stanford talk that AGI could arrive within 3 years, defining AGI as a system that outperforms human experts across most economically valuable tasks. He acknowledged that alignment work is not yet keeping pace with capability gains. The comment triggered debate on whether OpenAI is shifting its safety messaging.",
            },
            {
                "title": "Efficient Long-Context Transformers: Sparse Attention Without Accuracy Loss",
                "url": "https://arxiv.org/abs/2604.20045",
                "source_name": "arXiv cs.AI",
                "source_tier": 1,
                "published_at": "2026-04-30T00:00:00+00:00",
                "score": 7,
                "score_reason": "Sparse attention is a core efficiency technique for long-context models",
                "category": "ai_news",
                "summary": "A new sparse attention pattern called BlockSparse-H achieves 94% of full-attention MMLU performance at 128K context while using 3.2x less memory. The pattern is hardware-aligned for A100/H100 tensor core layouts. The authors provide a drop-in PyTorch implementation.",
            },
            {
                "title": "LangChain Adds Native Streaming for Multi-Agent Handoffs",
                "url": "https://news.ycombinator.com/item?id=43000002",
                "source_name": "HackerNews",
                "source_tier": 2,
                "published_at": "2026-04-30T14:00:00+00:00",
                "score": 7,
                "score_reason": "Directly relevant to LangGraph/LangChain-based agent development",
                "category": "ai_news",
                "summary": "LangChain's v0.3.5 release adds first-class streaming support across agent handoff boundaries, eliminating the buffering delay when one agent passes state to another. LangGraph graphs automatically inherit streaming; no code changes needed for existing graphs. Latency on multi-agent pipelines drops by ~40% in early benchmarks.",
            },
            {
                "title": "Resume Red Flags That Get AI Engineers Screened Out Immediately",
                "url": "https://techcrunch.com/2026/04/29/ai-engineer-resume-red-flags",
                "source_name": "TechCrunch AI",
                "source_tier": 1,
                "published_at": "2026-04-29T12:00:00+00:00",
                "score": 6,
                "score_reason": "Actionable resume guidance for AI engineering job search",
                "category": "career",
                "summary": "Recruiting leads at five AI-first companies listed the patterns that trigger immediate rejection: listing models used without describing the problem solved, claiming ownership of teams of 50 for a 2-year engineer, and no evidence of working with real data. Engineers who pass screening show concrete numbers: latency improvements, cost reductions, and scale.",
            },
            {
                "title": "Anthropic Raises $3.5B, Valuation Reaches $61.5B",
                "url": "https://techcrunch.com/2026/04/30/anthropic-raises-3b",
                "source_name": "TechCrunch AI",
                "source_tier": 1,
                "published_at": "2026-04-30T11:00:00+00:00",
                "score": 6,
                "score_reason": "Funding at this scale signals the Claude ecosystem will grow significantly",
                "category": "ceo_update",
                "summary": "Anthropic closed a $3.5B Series F at a $61.5B valuation, led by Google and joined by Amazon and Spark Capital. The funds are allocated to frontier model training and expanding Claude's enterprise API. Dario Amodei said the raise will support safety research at the same pace as capabilities.",
            },
        ],
    },
    {
        "timestamp": "2026-05-01T07:01:44.819372+00:00",
        "articles": [
            {
                "title": "Claude 4 Sonnet Benchmarks: Best Coding Model for Under $5/M Tokens",
                "url": "https://venturebeat.com/ai/claude-4-sonnet-coding-benchmark",
                "source_name": "VentureBeat AI",
                "source_tier": 1,
                "published_at": "2026-05-01T07:00:00+00:00",
                "score": 9,
                "score_reason": "Top-tier model release with direct implications for production AI stacks",
                "category": "ai_news",
                "summary": "Claude Sonnet 4.6 tops SWE-bench Verified at 72.1% while staying below $5/million input tokens, making it the best value coding model available. Anthropic's extended thinking mode is now default-enabled for all tool-use calls. Engineers using Claude in agentic coding pipelines should test the new model immediately.",
            },
            {
                "title": "Agentic RAG: Replacing Static Retrieval with Tool-Calling Agents",
                "url": "https://arxiv.org/abs/2605.00010",
                "source_name": "arXiv cs.AI",
                "source_tier": 1,
                "published_at": "2026-05-01T00:00:00+00:00",
                "score": 8,
                "score_reason": "Directly relevant to RAG engineering; replaces retrieval with agentic loop",
                "category": "ai_news",
                "summary": "This paper frames RAG as a multi-step agentic process where the LLM issues sub-queries, evaluates retrieved chunks, and decides whether to retrieve more before answering. On multi-hop QA benchmarks, agentic RAG outperforms one-shot retrieval by 23 F1 points. The authors provide a LangGraph reference implementation.",
            },
            {
                "title": "The AI Engineer Salary Report 2026: Ranges, Gaps, and What Moves the Number",
                "url": "https://techcrunch.com/2026/05/01/ai-engineer-salary-2026",
                "source_name": "TechCrunch AI",
                "source_tier": 1,
                "published_at": "2026-05-01T08:00:00+00:00",
                "score": 8,
                "score_reason": "Direct job market data for AI engineering roles in current job hunt",
                "category": "career",
                "summary": "Based on 1,400 verified offers, AI engineers at mid-level average $195K total comp in the US, with the top quartile at $280K. The biggest salary predictor after role level is whether the engineer has shipped a production system used by more than 1,000 users. LLM fine-tuning and RAG experience add ~$20K over average.",
            },
            {
                "title": "Self-Consistency Prompting Still Beats Chain-of-Thought on Hard Math",
                "url": "https://arxiv.org/abs/2605.00111",
                "source_name": "arXiv cs.AI",
                "source_tier": 1,
                "published_at": "2026-05-01T00:00:00+00:00",
                "score": 7,
                "score_reason": "Practical prompting technique with production applicability",
                "category": "ai_news",
                "summary": "A systematic comparison across 12 reasoning benchmarks confirms that sampling 8-16 diverse chain-of-thought solutions and taking a majority vote outperforms single extended-thinking passes by 6-9% on competition math. The effect shrinks for problems models already get right 90%+ of the time. Cost-effective for high-stakes decisions.",
            },
            {
                "title": "Postgres + pgvector vs. Pinecone: A Production Comparison at 50M Vectors",
                "url": "https://news.ycombinator.com/item?id=43100001",
                "source_name": "HackerNews",
                "source_tier": 2,
                "published_at": "2026-05-01T14:00:00+00:00",
                "score": 8,
                "score_reason": "Directly useful for RAG system infrastructure decisions",
                "category": "ai_news",
                "summary": "An engineering team at 50M vectors shares latency and cost data: pgvector with HNSW indexes hits 8ms P95 for ANN queries versus Pinecone's 6ms, but Postgres total cost is 60% lower at that scale. The team migrated from Pinecone after hitting $8K/month. The post covers index tuning, connection pooling, and where Pinecone still wins.",
            },
            {
                "title": "Mistral 8x22B Fine-Tuning Guide: Getting Production Quality on 2 A100s",
                "url": "https://venturebeat.com/ai/mistral-8x22b-finetuning-2-a100",
                "source_name": "VentureBeat AI",
                "source_tier": 1,
                "published_at": "2026-05-01T09:00:00+00:00",
                "score": 7,
                "score_reason": "Practical fine-tuning guide for engineers without large GPU budgets",
                "category": "ai_news",
                "summary": "A step-by-step guide for fine-tuning Mistral 8x22B using QLoRA on two A100 80GB GPUs in under 24 hours. Key techniques: rank-16 adapters on attention only (not MLP), gradient checkpointing, flash attention 2, and bf16 training. The author achieves production-quality domain adaptation on 50K examples for under $400 in cloud compute.",
            },
            {
                "title": "Google Fires 200 in Cloud AI Division, Shifts Headcount to Gemini Teams",
                "url": "https://techcrunch.com/2026/05/01/google-layoffs-cloud-ai",
                "source_name": "TechCrunch AI",
                "source_tier": 1,
                "published_at": "2026-05-01T10:00:00+00:00",
                "score": 6,
                "score_reason": "Signals Google restructuring AI investment toward Gemini — affects job market",
                "category": "ceo_update",
                "summary": "Google eliminated 200 roles in Cloud AI infrastructure as part of a reallocation to the Gemini product team. The cuts affect ML platform engineers who built tooling for third-party models. A Google spokesperson said the company is consolidating AI development around first-party models and Vertex AI.",
            },
            {
                "title": "Eval-Driven Development: Building LLM Apps That Actually Improve Over Time",
                "url": "https://arxiv.org/abs/2605.00222",
                "source_name": "arXiv cs.AI",
                "source_tier": 1,
                "published_at": "2026-05-01T00:00:00+00:00",
                "score": 8,
                "score_reason": "Framework for building reliable LLM applications — core production AI skill",
                "category": "ai_news",
                "summary": "The paper proposes treating LLM application development as a red-green cycle: write failing evals first, then improve prompts/models until they pass, then ship. Applied to 6 internal production apps, this approach reduced regression rate by 71% compared to ad-hoc prompt engineering. The eval framework is open-sourced.",
            },
            {
                "title": "Breaking into AI Engineering Without a PhD: What Actually Works in 2026",
                "url": "https://news.ycombinator.com/item?id=43100002",
                "source_name": "HackerNews",
                "source_tier": 2,
                "published_at": "2026-05-01T18:00:00+00:00",
                "score": 7,
                "score_reason": "Direct career transition advice relevant to current job hunt",
                "category": "career",
                "summary": "A hiring manager at a Series B AI company explains that the PhD premium has collapsed since 2024 — engineering teams need builders, not researchers. The winning profile in 2026 is 2+ shipped LLM features with documented evals, not academic credentials. The post includes a GitHub portfolio checklist that passes internal bar-raiser review.",
            },
            {
                "title": "Ilya Sutskever's SSI Raises $2B to Build Safe Superintelligence",
                "url": "https://techcrunch.com/2026/05/01/ssi-raises-2b",
                "source_name": "TechCrunch AI",
                "source_tier": 1,
                "published_at": "2026-05-01T11:30:00+00:00",
                "score": 6,
                "score_reason": "Major funding signals continued investment in frontier AI safety research",
                "category": "ceo_update",
                "summary": "Ilya Sutskever's Safe Superintelligence Inc. closed a $2B Series B at an undisclosed valuation, with backing from Sequoia, a16z, and sovereign wealth funds. SSI remains the only major AI lab with no public product — the entire operation is focused on alignment research and internal model development. Sutskever reiterated no product launch plans.",
            },
        ],
    },
    {
        "timestamp": "2026-05-02T06:49:14.295457+00:00",
        "articles": [
            {
                "title": "When Your LLM Reaches End-of-Life: A Framework for Confident Model Migration",
                "url": "https://arxiv.org/abs/2604.27082",
                "source_name": "arXiv cs.AI",
                "source_tier": 1,
                "published_at": "2026-05-02T00:00:00+00:00",
                "score": 8,
                "score_reason": "Critical real-world engineering problem for anyone running LLM infrastructure",
                "category": "ai_news",
                "summary": "Researchers present a Bayesian statistical framework for migrating production LLM systems when models reach end-of-life. The framework uses held-out regression tests to estimate performance delta before full rollout. This addresses a critical real-world challenge directly applicable to engineers running LLM infrastructure.",
            },
            {
                "title": "Think it, Run it: Autonomous ML Pipeline Generation via Self-Healing Multi-Agent AI",
                "url": "https://arxiv.org/abs/2604.27096",
                "source_name": "arXiv cs.AI",
                "source_tier": 1,
                "published_at": "2026-05-02T00:00:00+00:00",
                "score": 8,
                "score_reason": "Directly relevant to agentic AI systems and ML automation",
                "category": "ai_news",
                "summary": "A multi-agent architecture automates end-to-end ML pipeline generation from natural language goals and datasets, handling feature engineering, model selection, and hyperparameter tuning autonomously. Each specialist agent can self-repair its own failures using an error reflection loop. On AutoML benchmarks the system matches human-designed pipelines 78% of the time.",
            },
            {
                "title": "LangGraph 2.0 Released: Persistent Memory and Human-in-the-Loop Checkpoints",
                "url": "https://venturebeat.com/ai/langgraph-2-released",
                "source_name": "VentureBeat AI",
                "source_tier": 1,
                "published_at": "2026-05-02T08:00:00+00:00",
                "score": 9,
                "score_reason": "Major version of the exact framework used in this project",
                "category": "ai_news",
                "summary": "LangGraph 2.0 ships persistent cross-thread memory, structured human-in-the-loop interrupts, and a new time-travel debugger that replays any graph execution from any checkpoint. The API is backwards-compatible with 1.x; upgrading requires only changing the import path for memory stores. The LangGraph Studio visual debugger is now GA.",
            },
            {
                "title": "RAG vs. Fine-Tuning: A Practical Decision Framework for Production LLMs",
                "url": "https://techcrunch.com/2026/05/02/rag-vs-finetuning-framework",
                "source_name": "TechCrunch AI",
                "source_tier": 1,
                "published_at": "2026-05-02T09:00:00+00:00",
                "score": 8,
                "score_reason": "Core AI engineering decision framework applicable to almost every project",
                "category": "ai_news",
                "summary": "A decision tree for choosing RAG versus fine-tuning based on four questions: update frequency, data volume, latency budget, and whether the task is knowledge retrieval or style/behavior change. The authors find that 80% of production use cases are solved better by RAG, with fine-tuning reserved for tone, format, and domain-specific reasoning.",
            },
            {
                "title": "Staff AI Engineer at Stripe: What the Role Actually Looks Like Day-to-Day",
                "url": "https://news.ycombinator.com/item?id=43200001",
                "source_name": "HackerNews",
                "source_tier": 2,
                "published_at": "2026-05-01T20:00:00+00:00",
                "score": 7,
                "score_reason": "Concrete description of a target senior AI engineering role",
                "category": "career",
                "summary": "A staff AI engineer at Stripe describes a week split between writing evaluation harnesses, reviewing prompt changes in code review, debugging latency regressions in fraud detection models, and writing design docs for new LLM-powered features. The post emphasizes that 70% of the work is measurement and reliability, not model research.",
            },
            {
                "title": "Structured Output Reliability: Why JSON Mode Still Fails at Scale",
                "url": "https://arxiv.org/abs/2605.00330",
                "source_name": "arXiv cs.AI",
                "source_tier": 1,
                "published_at": "2026-05-02T00:00:00+00:00",
                "score": 7,
                "score_reason": "JSON parsing failures are a real production reliability issue in LLM pipelines",
                "category": "ai_news",
                "summary": "An analysis of 2M production JSON-mode calls finds a 3.4% failure rate from schema violations, truncation, and nested structure corruption — not from the model ignoring JSON mode. The paper proposes a constrained decoding layer that reduces failures to 0.1% with no latency increase. Reference implementation released for vLLM and TGI.",
            },
            {
                "title": "How to Negotiate Your First AI Engineering Offer: Data from 300 Offers",
                "url": "https://venturebeat.com/ai/ai-engineer-offer-negotiation",
                "source_name": "VentureBeat AI",
                "source_tier": 1,
                "published_at": "2026-05-02T07:00:00+00:00",
                "score": 7,
                "score_reason": "Concrete negotiation data directly relevant to active job hunt",
                "category": "career",
                "summary": "Analysis of 300 anonymized AI engineering offers shows that 84% of initial offers have room to negotiate, with an average gain of $22K base by countering once. The data shows equity negotiation is more effective than base at companies past Series C. The most effective counter is a competing offer, followed by demonstrating a specific competing offer number.",
            },
            {
                "title": "Attention Is All You Need — Seven Years Later: What the Transformer Got Wrong",
                "url": "https://arxiv.org/abs/2605.00400",
                "source_name": "arXiv cs.AI",
                "source_tier": 1,
                "published_at": "2026-05-02T00:00:00+00:00",
                "score": 7,
                "score_reason": "Historical perspective on transformer limitations informs current architecture choices",
                "category": "ai_news",
                "summary": "On the 7th anniversary of 'Attention Is All You Need', original authors reflect on what the transformer architecture got wrong: quadratic attention complexity, fixed positional encoding, and no explicit memory mechanism. The paper argues that hybrid attention-state-space models like Mamba-2 address all three limitations and represent the next generation of sequence models.",
            },
            {
                "title": "Microsoft Satya Nadella: Copilot Will Replace 30% of SWE Tasks Within 2 Years",
                "url": "https://techcrunch.com/2026/05/02/nadella-copilot-30-percent",
                "source_name": "TechCrunch AI",
                "source_tier": 1,
                "published_at": "2026-05-02T10:00:00+00:00",
                "score": 6,
                "score_reason": "CEO statement about AI replacing engineering work directly relevant to job market",
                "category": "ceo_update",
                "summary": "Satya Nadella told analysts that Microsoft's internal data shows GitHub Copilot already handles 30% of new code committed at Microsoft, and he expects that figure to reach 50% within 18 months. He defined 'replacement' as tasks handled with no human edits to the generated output. AI engineering roles (building the systems) are explicitly excluded from his projection.",
            },
            {
                "title": "Sources: Anthropic $900B+ Valuation Round Could Happen Within 2 Weeks",
                "url": "https://techcrunch.com/2026/04/30/anthropic-900b-valuation",
                "source_name": "TechCrunch AI",
                "source_tier": 1,
                "published_at": "2026-04-30T14:00:00+00:00",
                "score": 8,
                "score_reason": "Valuation at this level signals the Claude ecosystem will scale dramatically",
                "category": "ceo_update",
                "summary": "Anthropic is moving quickly on a $900B+ funding round that could close within two weeks according to sources familiar with the deal. The valuation jump from $61B to $900B+ reflects explosive growth in the Claude API ecosystem and enterprise adoption. Signals strong institutional confidence in frontier models as infrastructure.",
            },
        ],
    },
]


def _fill_defaults(articles: list[dict]) -> list[dict]:
    return [{**a, "description": a.get("description", "")} for a in articles]


def main() -> None:
    db.init_db()

    for run in RUNS:
        run_id = db.save_run(run["timestamp"], _fill_defaults(run["articles"]))
        date = run["timestamp"][:10]
        print(f"Seeded run {date} — {len(run['articles'])} articles (id={run_id})")

    print("Done. DB ready for Streamlit Cloud deployment.")


if __name__ == "__main__":
    main()
